# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.synced_folder "../ansible", "/home/vagrant/ansible"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt update
    apt upgrade -y
    apt install -y git ansible
    touch /home/vagrant/.ssh/id_rsa.pub
    ansible-playbook ansible/install_kitchen.yml
  SHELL
end
